Implementing Currency Toggle Feature
CSC207-2022F-UofT/course-project-poppin-party-peacocks pull request #114
Opened 2022-12-05 20:46 UTC by kevinle623

Implemented general logic for currency toggle button such that everytime the user class changes the currency, all the items within the wishlists will change currency. Also, added an attribute to Item Searcher and Item Update Checker  to consider currency of User option.

2022-12-05 21:52 UTC, Ljime requested changes

2022-12-05 21:52 UTC, Ljime commented on src/main/java/Entities/Item.java
> +    public void setProductCurrency(String newCurrency) {
Why are we creating new logic here? The currency use case exists to adhere to clean architecture with logic already in it.

2022-12-05 21:52 UTC, Ljime commented on src/main/java/Entities/User.java
> +        if (currency.equals("CAD")){
This needs to go into the currency usecase as well for clean architecture

2022-12-07 18:37 UTC, AlexChenl3 approved these changes

2022-12-07 18:41 UTC, linajin03 approved these changes

2022-12-07 18:48 UTC, merged