UserRegister functionality and tests
CSC207-2022F-UofT/course-project-poppin-party-peacocks pull request #51
Opened 2022-11-24 03:58 UTC by linajin03

2022-11-24 07:28 UTC, AlexChenl3 submitted a review, later dismissed
everthing looks good, i like the usernames u picked out for ur tests

2022-11-24 18:23 UTC, Ljime requested changes
Overall logic looks good, only thing is that some functions doc strings are missing the @param part of the docstring

2022-11-24 18:23 UTC, Ljime commented on src/main/java/UserRegister.java
> +        if (this.inputs.checkUserExists()){
Docstring parameter missing here

2022-11-24 18:23 UTC, Ljime commented on src/main/java/UserRegistrationFailed.java
> +        super(errorMessage);
Here as well

2022-11-24 18:23 UTC, Ljime commented on src/main/java/UserRegisterResponseFormatter.java
> +    public UserRegisterInputs showFailure(String failMessage) {
Same here

2022-11-25 21:15 UTC, chinchinjim approved these changes
looks good, like the clean architecture structure! ditto on what hermanns said about the docstrings, you could also add docstrings to the testing functions but its not necessary since the function names are pretty descriptive already. nice work Lina! :)

2022-11-26 00:13 UTC, Ljime approved these changes

2022-11-26 00:13 UTC, AlexChenl3 approved these changes
reapproving

2022-11-26 00:14 UTC, kevinle623 approved these changes
great job implementing the user account logic, looks good to me

2022-11-26 00:14 UTC, merged