New PR for factory comparators
CSC207-2022F-UofT/course-project-poppin-party-peacocks pull request #99
Opened 2022-12-03 02:39 UTC by AlexChenl3

due to merging issues with main, PR88 was closed and a new branch was formed from before the merging issues. from PR88:

Currently, our testing files are all in one folder, which is not very clean architecture. To fix this, i created some more folders that better represents clean architecture and refactored all of our current testing files into their respective folders. After refactoring, there were some unused import statements that i got rid of as well.

Note: currently, LoginActionTest, UserRegistionTest are not in any folders yet because their main java file have not been put into any clean architecture folders. Another PR to update this issue will be made once LoginActionTest, UserRegistionTest, and maybe more test files are created and have been placed into their respective folders.

Edit: Another issue happend with DataBaseTest not working, Herman decided to move it out of the DataBaseTest folder for now. This issue will be added into the same issue as LoginActionTest and UserRegistionTest

Edit 2: Fixed the issue with DataBaseTests not working by removing the java folder and refactoring the clean architecture testing folders directly inside of test folder. LoginActionTest and UserRegistionTest also got refactored so no need for another issue for those two files, although there still could be more new testing files that are created so that issue will stay open for now

2022-12-03 03:01 UTC, chinchinjim approved these changes
Nice job adding documentation + clean arch into the code, makes it a lot more readable now :) some tests aren't passing, but they'll be fixed in a future pr so other than that it looks good

2022-12-03 04:22 UTC, Ljime requested changes
The changes still do not comply with clean architecture, we are not allowed to create controllers or anything above the entity layer inside of an entity. The sorting functions should not be in Wishlist. It sthould be in controller where a controller is created and called from the UI

2022-12-03 04:24 UTC, Ljime commented on src/main/java/Entities/ProductComparatorController.java
> +            case "date":
This switch case can be simplied to return productFactory.createComparator(word.toLowerCase());

2022-12-05 17:25 UTC, kevinle623 submitted a review, later dismissed

2022-12-05 23:41 UTC, AlexChenl3 commented
also TODO: sortListTest and sortingHelperTest in ProductComparatorControllerTest

2022-12-06 02:19 UTC, Ljime requested changes

2022-12-06 02:19 UTC, Ljime commented on src/main/java/Controller/ProductComparatorController.java
> +public class ProductComparatorController implements ProductList {
Why does this implement product list and have add and remove item functions? This is a controller just for sorting is it not?

2022-12-06 02:19 UTC, Ljime commented on src/main/java/Controller/ProductComparatorController.java
> +    }
Why are there getters and setters here?

2022-12-07 04:08 UTC, DavidZ79 approved these changes

2022-12-07 04:12 UTC, Ljime approved these changes

2022-12-07 04:20 UTC, linajin03 approved these changes

2022-12-07 04:21 UTC, merged

2022-12-07 04:23 UTC, PyroPoro approved these changes
Good implementation of the factory design pattern! For the tests, it doesnt seem like you need to test two lists that are identical and call the same method on both lists as one is sufficient, but it doesn't hurt to test both.